import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision.models import resnet18
from transformers import AutoModel, ChineseCLIPModel


class CrossModalTransformer(nn.Module):
    def __init__(self, model_dim: int, layer_num: int, head_num: int):
        super().__init__()
        self.text_to_image = nn.ModuleList(
            [nn.MultiheadAttention(model_dim, head_num, batch_first=True) for _ in range(layer_num)]
        )
        self.image_to_text = nn.ModuleList(
            [nn.MultiheadAttention(model_dim, head_num, batch_first=True) for _ in range(layer_num)]
        )
        self.text_norm1 = nn.ModuleList([nn.LayerNorm(model_dim) for _ in range(layer_num)])
        self.image_norm1 = nn.ModuleList([nn.LayerNorm(model_dim) for _ in range(layer_num)])
        self.text_norm2 = nn.ModuleList([nn.LayerNorm(model_dim) for _ in range(layer_num)])
        self.image_norm2 = nn.ModuleList([nn.LayerNorm(model_dim) for _ in range(layer_num)])
        ff_dim = model_dim * 4
        self.text_ffn = nn.ModuleList(
            [nn.Sequential(nn.Linear(model_dim, ff_dim), nn.ReLU(), nn.Linear(ff_dim, model_dim)) for _ in range(layer_num)]
        )
        self.image_ffn = nn.ModuleList(
            [nn.Sequential(nn.Linear(model_dim, ff_dim), nn.ReLU(), nn.Linear(ff_dim, model_dim)) for _ in range(layer_num)]
        )

    def forward(self, text_features, image_features):
        for t2i, i2t, t_ffn, i_ffn, t_ln1, i_ln1, t_ln2, i_ln2 in zip(
            self.text_to_image,
            self.image_to_text,
            self.text_ffn,
            self.image_ffn,
            self.text_norm1,
            self.image_norm1,
            self.text_norm2,
            self.image_norm2,
        ):
            text_attended, _ = t2i(text_features, image_features, image_features)
            image_attended, _ = i2t(image_features, text_features, text_features)
            text_features = t_ln1(text_features + text_attended)
            image_features = i_ln1(image_features + image_attended)
            text_features = t_ln2(text_features + t_ffn(text_features))
            image_features = i_ln2(image_features + i_ffn(image_features))
        return text_features, image_features


class TextSemanticEncoder(nn.Module):
    """
    BERT encodes global semantics, while entity tokens from a fine-tuned NER
    pipeline are mapped by CLIP text encoder for cross-modal alignment.
    """

    def __init__(self, args):
        super().__init__()
        self.clip = None
        self.bert = AutoModel.from_pretrained(
            args.bert_model_name,
            local_files_only=args.local_files_only,
            use_safetensors=False,
        )
        try:
            self.clip = ChineseCLIPModel.from_pretrained(
                args.clip_model_name,
                local_files_only=args.local_files_only,
                use_safetensors=False,
            )
            self.clip_dim = self.clip.config.projection_dim
        except OSError:
            self.clip_dim = args.shared_feature_dim
        self.global_projector = nn.Linear(self.bert.config.hidden_size, self.clip_dim)
        self.entity_projector = nn.Linear(self.bert.config.hidden_size, self.clip_dim)

        if args.freeze_bert:
            for param in self.bert.parameters():
                param.requires_grad = False

        if self.clip is not None and args.freeze_clip_text:
            for param in self.clip.text_model.parameters():
                param.requires_grad = False
            for param in self.clip.text_projection.parameters():
                param.requires_grad = False

    def forward(self, text_input, entity_tokens):
        attention_mask = (text_input != 0).long()
        bert_outputs = self.bert(input_ids=text_input, attention_mask=attention_mask)
        global_feature = self.global_projector(bert_outputs.last_hidden_state[:, 0, :])

        batch_size, num_entities, entity_len = entity_tokens.shape
        flat_entities = entity_tokens.view(-1, entity_len)
        entity_attention_mask = (flat_entities != 0).long()
        if self.clip is not None:
            entity_features = self.clip.get_text_features(
                input_ids=flat_entities,
                attention_mask=entity_attention_mask,
            ).view(batch_size, num_entities, -1)
        else:
            entity_outputs = self.bert(input_ids=flat_entities, attention_mask=entity_attention_mask)
            entity_features = self.entity_projector(entity_outputs.last_hidden_state[:, 0, :]).view(batch_size, num_entities, -1)
        return global_feature, entity_features


class VisualObjectEncoder(nn.Module):
    """
    Consumes image regions generated by a Faster R-CNN detector in preprocessing.
    """

    def __init__(self, clip_model, feature_dim: int, freeze_clip_image: bool = False):
        super().__init__()
        self.clip = clip_model
        self.feature_dim = feature_dim
        if self.clip is None:
            backbone = resnet18(weights=None)
            self.backbone = nn.Sequential(*list(backbone.children())[:-1])
            self.projector = nn.Linear(backbone.fc.in_features, feature_dim)
        elif freeze_clip_image:
            for param in self.clip.vision_model.parameters():
                param.requires_grad = False
            for param in self.clip.visual_projection.parameters():
                param.requires_grad = False

    def forward(self, crop_input):
        batch_size, region_num = crop_input.shape[:2]
        flat_regions = crop_input.view(-1, 3, 224, 224)
        if self.clip is not None:
            region_features = self.clip.get_image_features(pixel_values=flat_regions)
        else:
            visual_features = self.backbone(flat_regions).flatten(1)
            region_features = self.projector(visual_features)
        return region_features.view(batch_size, region_num, -1)


class ConflictFeatureEncoder(nn.Module):
    def __init__(self, conv_out: int, conv_kernel, crop_num: int):
        super().__init__()
        self.convs = nn.ModuleList(
            [nn.Conv2d(in_channels=1, out_channels=conv_out, kernel_size=(kernel, crop_num)) for kernel in conv_kernel]
        )
        self.logit_scale = 100
        self.consistency_dim = len(conv_kernel) * conv_out

    def forward(self, text_features, image_features):
        norm_text = F.normalize(text_features, dim=-1)
        norm_image = F.normalize(image_features, dim=-1)
        similarity = torch.matmul(norm_text, norm_image.transpose(1, 2))
        scaled_similarity = (self.logit_scale * similarity).unsqueeze(1)

        consistency_maps = [F.relu(conv(scaled_similarity)).squeeze(3) for conv in self.convs]
        consistency_feature = torch.cat(
            [F.avg_pool1d(feature_map, feature_map.size(2)).squeeze(2) for feature_map in consistency_maps],
            dim=1,
        )

        max_sim_per_entity = similarity.max(dim=2).values
        mean_sim = similarity.mean(dim=(1, 2))
        missing_ratio = (max_sim_per_entity < 0.45).float().mean(dim=1)
        sim_variance = torch.var(max_sim_per_entity, dim=1, unbiased=False)
        max_sim = max_sim_per_entity.max(dim=1).values
        min_sim = max_sim_per_entity.min(dim=1).values
        conflict_vector = torch.stack([mean_sim, missing_ratio, sim_variance, max_sim, min_sim], dim=1)

        return {
            "global_text": text_features[:, 0, :],
            "global_image": image_features[:, 0, :],
            "consistency_feature": consistency_feature,
            "conflict_vector": conflict_vector,
            "similarity_matrix": similarity,
        }


class MultimodalClassifier(nn.Module):
    def __init__(self, clip_dim: int, consistency_dim: int, dropout_p: float,
                 use_text: bool = True, use_image: bool = True, use_conflict: bool = True):
        super().__init__()
        self.use_text = use_text
        self.use_image = use_image
        self.use_conflict = use_conflict

        # ========== Text Head ==========
        if use_text:
            self.text_head = nn.Sequential(
                nn.Linear(clip_dim, 256),
                nn.ReLU(),
                nn.Linear(256, 64),
                nn.ReLU(),
            )

        # ========== Image Head ==========
        if use_image:
            self.image_head = nn.Sequential(
                nn.Linear(clip_dim, 256),
                nn.ReLU(),
                nn.Linear(256, 64),
                nn.ReLU(),
            )

        # ========== Consistency Head ==========
        if consistency_dim > 0:
            self.consistency_head = nn.Sequential(
                nn.Linear(consistency_dim, 128),
                nn.ReLU(),
                nn.Linear(128, 64),
                nn.ReLU(),
            )

        # ========== Conflict Head ==========
        if use_conflict:
            self.conflict_head = nn.Sequential(
                nn.Linear(5, 32),
                nn.ReLU(),
            )

        self.dropout = nn.Dropout(dropout_p)

        # ========== Calculate Fusion Input Dimension ==========
        fusion_input_dim = 0
        if use_text:
            fusion_input_dim += 64
        if use_image:
            fusion_input_dim += 64
        if consistency_dim > 0:
            fusion_input_dim += 64
        if use_conflict:
            fusion_input_dim += 32

        # Ensure fusion_input_dim is at least 64
        fusion_input_dim = max(fusion_input_dim, 64)

        self.fusion = nn.Sequential(
            nn.Linear(fusion_input_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout_p),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 2),
        )

    def forward(self, features):
        feature_list = []

        if self.use_text:
            text_feature = self.dropout(self.text_head(features["global_text"]))
            feature_list.append(text_feature)

        if self.use_image:
            image_feature = self.dropout(self.image_head(features["global_image"]))
            feature_list.append(image_feature)

        if hasattr(self, 'consistency_head') and features["consistency_feature"].shape[-1] > 0:
            consistency_feature = self.dropout(self.consistency_head(features["consistency_feature"]))
            feature_list.append(consistency_feature)

        if self.use_conflict and features["conflict_vector"].shape[-1] > 0:
            conflict_feature = self.dropout(self.conflict_head(features["conflict_vector"]))
            feature_list.append(conflict_feature)

        # If no features selected (extreme ablation), use text as fallback
        if not feature_list:
            feature_list.append(torch.zeros(features["global_text"].shape[0], 64, device=features["global_text"].device))

        fused_feature = torch.cat(feature_list, dim=-1)
        logits = self.fusion(fused_feature)
        return F.log_softmax(logits, dim=-1)


class MultimodalFakeNewsDetector(nn.Module):
    def __init__(self, args):
        super().__init__()
        # ========== Ablation Control Flags ==========
        self.ablation_mode = getattr(args, 'ablation_mode', 'full')
        self.use_cross_modal = self.ablation_mode not in ['no_cross_modal', 'lite']
        self.use_conflict = self.ablation_mode not in ['no_conflict', 'lite']
        self.use_text = True  # Always use text
        self.use_image = True  # Always use image (for fair comparison)
        self.use_entity = self.ablation_mode not in ['no_entity', 'lite']
        self.use_bert = True  # Always use BERT

        # ========== Text Encoder ==========
        self.text_encoder = TextSemanticEncoder(args)
        if not self.use_bert:
            # Freeze BERT when ablating text encoder
            for param in self.text_encoder.bert.parameters():
                param.requires_grad = False

        # ========== Visual Encoder ==========
        if self.use_image:
            self.visual_encoder = VisualObjectEncoder(
                clip_model=self.text_encoder.clip,
                feature_dim=self.text_encoder.clip_dim,
                freeze_clip_image=args.freeze_clip_image,
            )

        # ========== Cross Modal Transformer ==========
        if self.use_cross_modal:
            self.cross_modal_transformer = CrossModalTransformer(
                model_dim=self.text_encoder.clip_dim,
                layer_num=args.layer_num,
                head_num=args.num_heads,
            )

        # ========== Conflict Feature Encoder ==========
        if self.use_conflict:
            self.conflict_encoder = ConflictFeatureEncoder(
                conv_out=args.conv_out,
                conv_kernel=args.conv_kernel,
                crop_num=args.crop_num,
            )
            consistency_dim = self.conflict_encoder.consistency_dim
        else:
            consistency_dim = 0

        # ========== Classifier ==========
        self.classifier = MultimodalClassifier(
            clip_dim=self.text_encoder.clip_dim,
            consistency_dim=consistency_dim,
            dropout_p=args.dropout_p,
            use_text=self.use_text,
            use_image=self.use_image,
            use_conflict=self.use_conflict,
        )

    def encode_modalities(self, data):
        global_text_feature, entity_features = self.text_encoder(data["text_input"], data["entity_tokens"])

        if self.use_image:
            image_features = self.visual_encoder(data["crop_input"])
        else:
            # Dummy image features for text-only mode
            image_features = None

        if not self.use_entity:
            # Use only global text feature
            entity_features = torch.zeros_like(global_text_feature).unsqueeze(1)

        return global_text_feature, entity_features, image_features

    def forward_from_encoded(self, global_text_feature, entity_features, image_features):
        # Build text sequence
        text_sequence = torch.cat([global_text_feature.unsqueeze(1), entity_features], dim=1)

        # Cross-modal transformation
        if self.use_cross_modal and image_features is not None:
            aligned_text, aligned_image = self.cross_modal_transformer(text_sequence, image_features)
        else:
            aligned_text = text_sequence
            aligned_image = image_features

        # Conflict encoding
        if self.use_conflict and aligned_image is not None:
            features = self.conflict_encoder(aligned_text, aligned_image)
        else:
            # Build minimal features dict for classifier
            features = {
                "global_text": aligned_text[:, 0, :],
                "global_image": aligned_image[:, 0, :] if aligned_image is not None else torch.zeros_like(aligned_text[:, 0, :]),
                "consistency_feature": torch.zeros(aligned_text.size(0), 0, device=aligned_text.device),
                "conflict_vector": torch.zeros(aligned_text.size(0), 0, device=aligned_text.device),
            }

        return self.classifier(features)

    def forward(self, data):
        global_text_feature, entity_features, image_features = self.encode_modalities(data)
        return self.forward_from_encoded(global_text_feature, entity_features, image_features)


C3N = MultimodalFakeNewsDetector